### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/SBM-ItemEatingSponge#1]
- [ ] Create Mod.class
- [ ] Add Gradle Script
- [ ] Add Block
- [ ] Add TileEntity
- [ ] Implement entity bound check
- [ ] Implement consuming items on ground
- [ ] Implement conusming items from entities (including players)
- [ ] Map of items to item type
- [ ] Implement type selection in TileEntity
- [ ] Add world generator (Very rare generation)
- [ ] Add animation for item floating to block
- [ ] Implement raytracing to make sure the animation works only on entities in sight
- [ ] Add sound effects for Tile consuming items
- [ ] Add crafting recipes
- [ ] Add item drops from entity
- [ ] Add leveling of Tile so it gets strong the more items it eats
